----

- name: Download Mailcow
  args: 
    executable: /bin/bash
  become: yes
  shell: |
      cd /opt && git clone https://github.com/mailcow/mailcow-dockerized.git
      cd mailcow-dockerized
  register: install_mailcow
  failed_when: "'error' in download_mailcow.stderr"

- name: Install Mailcow
  expect: 
    command: /opt/mailcow-dockerized/generate_config.sh
    responses:
      Question:
        -  mailcow
