---

- name: Turn off Windows Defender
  win_shell: "Set-MpPreference -DisableRealtimeMonitoring $true"
  
- name: Reboot Client for Defender changes
  win_reboot:
    msg: "Rebooting..."
    reboot_timeout: 45

- name: Look for Ghost directory  
  win_stat: 
    path: 'c:\tools\Ghost_Win'
  register: ghostdir

- name: Copy over Ghosts
  copy:
    src: ../Ghost_Win.zip
    dest: c:\Tools\.
  when: not ghostdir.stat.exists
  
- name: Unzip Ghost
  win_unzip:
    src: 'c:\Tools\Ghost_Win.zip'
    dest: 'c:\Tools\Ghost_Win'
    remote_src: yes
  when: not ghostdir.stat.exists  

- name: Check for Ghost directory
  win_stat: 
    path: 'c:\tools\Ghost_Win'
  register: ghostrun
  when: not ghostdir.stat.exists
  
- name: Removing zip file
  win_file:
    path: c:\Tools\Ghost_Win.zip
    state: absent
  when: not ghostdir.stat.exists  

- name: Make sure install finished before starting Ghost
  win_stat: 
    path: 'c:\tools\Ghost_Win'
  register: ghost_installed

- name: Starting Ghosts
  win_shell: "Start-Process -Filepath .\\ghosts.exe"
  args:
    chdir: 'c:\Tools\Ghost_Win'
  register: ghost
  failed_when: "'Exception' in ghost.stdout"
  when: ghost_installed.stat.exists

- name:  Print debug of ghost starting  
  debug: msg="{{ ghost.stdout_lines }}"
