---
language: python

# Use the new container infrastructure
sudo: required

env:
  global:
    - ROLE_NAME: samba
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: debian9
    - MOLECULE_DISTRO: fedora29
    - MOLECULE_DISTRO: ubuntu1804

#Enable docker support
services:
  - docker

install:
  - sudo apt-get update
  - sudo apt-get install bats curl smbclient samba-testsuite
  # Install dependencies for Molecule test
  - python3 -m pip install molecule yamllint ansible-lint docker
  # Check ansible, molecule and nmblookup version
  - ansible --version
  - molecule --version
  - nmblookup --version
  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

before_script:
  #Renames ansible-role-bind to bertvv.bind to make it match with Ansible Galaxy
  - cd ../
  - mv ansible-role-$ROLE_NAME bertvv.$ROLE_NAME
  - cd bertvv.$ROLE_NAME

script:
  #Run molecule test
  - molecule test 

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/