---

- name: Download Elastic Agent
  win_get_url:
    url: 'https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.0.0-windows-x86_64.zip'
    dest: 'C:\Tools\elastic-agent-8.0.0-windows-x86_64.zip'

- name: Unzip Elastic Agent
  win_unzip:
    src: 'c:\Tools\elastic-agent-8.0.0-windows-x86_64.zip'
    dest: 'c:\Tools'
    remote_src: yes

- name: Installing ElasticAgent
  #replace server IP:PORT and enrollment token from Fleet <Add Agent>
  win_shell: ".\\elastic-agent.exe install -f --insecure --url=https://192.168.56.101:8220 --enrollment-token=cmYzSU1uOEJVTUVMRWlscDNqZmU6NklYVXFlcVlUbTZGN3N2YjZ0eTg1Zw=="
  args:
    chdir: 'c:\Tools\elastic-agent-8.0.0-windows-x86_64'
  register: elastic_agent_install
  failed_when: "'Exception' in elastic_agent_install.stdout"

- debug: msg="{{ elastic_agent_install.stdout_lines }}"

- name: Removing zip file
  win_file:
    path: c:\Tools\elastic-agent-8.0.0-windows-x86_64.zip
    state: absent
